name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: kc868-a4.yaml,kc868-a8.yaml,kc868-a16.yaml,kc868-uair.yaml
      # CHANGEME: Set the name of your project here:
      name: Kincony Smart Home DIY
